site_name: Портфолио Чичерина Александра, студента первого курса.

theme:
    name: material
    features:
        - navigation.top
        - navigation.tabs
        - navigation.indexes

nav:
    - Главная: index.md

    - Мой гитхаб (переход): https://github.com/Chichetin/PYLabs/tree/main
    - Лабораторные прошлого полугодия:
        - Сравнения скорости факториалов: labs/old/lab1.md
        - Генератор бинарных деревьев: labs/old/lab2.md
        - Книжный каталог: labs/old/lab3.md