site_name: Портфолио Чичерина Александра, студента первого курса.

theme:
    name: material
    features:
        #- navigation.indexes
nav:
    - Главная: index.md
    - Об авторе: about.md
    - Мой гитхаб (переход): https://github.com/Chichetin/PYLabs/tree/main
    - Мой SourceCraft (переход): https://sourcecraft.dev/delox2/repos
    - Лабораторные прошлого полугодия:
        - Сравнения скорости факториалов: labs/old/lab1.md
        - Генератор бинарных деревьев: labs/old/lab2.md
        - Книжный каталог: labs/old/lab3.md
    - Лабораторные этого полугодия:
        - L1. Создание статического сайта: labs/lab1.md
        - L2. Работа с данными: labs/lab2.md
        - L3. CI/CD для статического сайта в SourceCraft: labs/lab3.md