site_name: Портфолио Чичерина Александра, студента первого курса.

theme:
    name: material
    features:
        - navigation.top
        - navigation.tabs
        - navigation.indexes

nav:
    - Главная: index.md
    - Мой гитхаб (переход): https://github.com/Chichetin/PYLabs/tree/main
    - Лабораторные:
        - Lab1: labs/lab1.md
        - Lab2: labs/lab2.md
        - Lab3: labs/lab3.md